fix(nuxt): transpile js-sha256 for cloudflare
Adds 'js-sha256' to the `build.transpile` array in `nuxt.config.ts`.

This is necessary to resolve a `TypeError: _interopRequireDefault is not a function` error that occurs on Cloudflare Pages. The error is caused by 'js-sha256' being a CommonJS module that needs to be explicitly transpiled to be compatible with the edge runtime environment.